### ISSUE TITLE
Capture `changed_files`, `additions`, `deletions` for a PR

### ISSUE THREAD

**Issue by rithviknishad** [ohcnetwork/leaderboard#144]
### Tasks

- [ ] For PRs, the files changed, lines addition and deletions should be captured by the scrapper (currently this is available only through the open graph image PR image generation as an image)

**Comment by khavinshankar** [comment]
@rithviknishad I think we can accomplish this using
`https://api.github.com/repos/{owner}/{repo}/compare/{base}...{head}` API

I just wanted to know the use case.
Wouldn't adding the file changes to JSON make them heavy over time?

**Comment by rithviknishad** [comment]
Yes, we'll need to implement pagination for the contributor activity page before that then. Otherwise, we'll easily get rate-limited if we open active contributors profile.

**Comment by rithviknishad** [comment]
Or maybe we could just leave it because that information is conveyed through the open graph image.
<img width="1324" alt="image" src="https://github.com/coronasafe/leaderboard/assets/25143503/422b45ab-5e74-47af-8714-5554b8187a2e">

The idea that I had in mine is that, we could at some point compute the total lines changed contributed by a user.

**Comment by rithviknishad** [comment]
The idea that I had in mine is that, we could at some point compute the total lines changed contributed by a user.

**Comment by khavinshankar** [comment]
Yes, that makes sense, then maybe we could just store the number of lines changed for each merged prs,
something like
```js
{ 
    lines: {
       added: number;
       removed: number;
       modified: number;
    }
}
```

**Comment by rhithesh** [comment]
I would like to work on this issue.
