### ISSUE TITLE
Identify issues linked to PRs from PR UI (graphql)

### ISSUE THREAD

**Issue by rithviknishad** [ohcnetwork/leaderboard#168]
Currently, there is no way to identify the issue number if the issue is linked (connected) using UI, so lets handle that part while moving to Graphql.

This is the event created for connection using UI
<img width="872" alt="image" src="https://github.com/coronasafe/leaderboard/assets/29787772/31120282-445b-4e9e-9a38-a375c13b9ec6">

If we want to do this now using rest API, we need to iterate through all the open issues and get the cross-referenced event which seems unnecessarily expensive.

PS: This is an issue only when the issue is connected with PR in PR's UI and not vice versa.

_Originally posted by @khavinshankar in https://github.com/coronasafe/leaderboard/issues/167#issuecomment-1853285978_

**Comment by aeswibon** [comment]
Is this issue still valid? If it is, then I would like to work on it.
