### ISSUE TITLE
Display Avg. turn around time for weekly leaderboard + Support sorting leaderboard by Turn Around Time

### ISSUE THREAD

**Issue by rithviknishad** [ohcnetwork/leaderboard#169]
- #167 has brought support for capturing turn around time for PRs and these are shown in the contributor profile page.

### Tasks 

- [ ] Show the average turn around time of contributors in weekly leaderboard (averaged for last 7 days events only)
- [ ] Add support for sorting leaderboard by this metric

<img width="1433" alt="image" src="https://github.com/coronasafe/leaderboard/assets/25143503/26c2d33b-3969-4e51-bc55-1eb08b72b1e4">

**Comment by kirtanchandak** [comment]
Hey @rithviknishad can may I work on this issue?

**Comment by kirtanchandak** [comment]
Hey @rithviknishad,

I ran the command `./load-fixtures.sh  `, `npm install --legacy-peer-deps` and then `npm run dev` but facing this issue in local dev setup, what can be the reason - 

![image](https://github.com/coronasafe/leaderboard/assets/92196705/d3bdfdcb-cdcf-4d04-b44f-12456bc14cfc)

**Comment by rithviknishad** [comment]
what does `ls data-repo/contributors/` output?

<img width="495" alt="image" src="https://github.com/coronasafe/leaderboard/assets/25143503/97945485-61f7-4d63-950f-323ba615cafc">

**Comment by rithviknishad** [comment]
Also, try in WSL instead. The symlinks works in unix based OS only IIRC

**Comment by kirtanchandak** [comment]
working on wsl
