### ISSUE TITLE
Enhancements to size of filters in Leaderboard page

### ISSUE THREAD

**Issue by rithviknishad** [ohcnetwork/leaderboard#317]
Currently, the size of each filter is not proper.

- [ ] Search filter should occupy 1/3rd of the total width
- [ ] And the rest of the items should be equally spaced (The role filter is taking unequal space)

<img width="1329" alt="image" src="https://github.com/coronasafe/leaderboard/assets/25143503/aeacb51d-3321-4281-b023-e5f38c62ff74">

**Comment by HARSHDOIPHODE** [comment]
can you please assign me

**Comment by HARSHDOIPHODE** [comment]
@rithviknishad  please review the PR

**Comment by rudra321** [comment]
Hey @rithviknishad , can I work on this issue ?

**Comment by rudra321** [comment]
I have done this. Is this okay can you please check and tell ?

![image](https://github.com/coronasafe/leaderboard/assets/59362723/abbbf9e4-1f90-4fc7-aa13-fbd5f1611d5f)

**Comment by rithviknishad** [comment]
Looking great!

**Comment by rudra321** [comment]
Okay thank you, I'll move ahead with it.

I also found something which might be an issue. Its my first time contributing so I'm not sure about this.

### **Previous Mobile view :** 
![image](https://github.com/coronasafe/leaderboard/assets/59362723/98e46695-c559-4f98-91b3-aad8b758cac8)
### **New Mobile View :** 
![image](https://github.com/coronasafe/leaderboard/assets/59362723/0a6c6acb-0dd3-4b65-9f81-c4e47f37edbd)

This new view is fine ? Or I revert it to previous version ? Or should I report it as a bug in issue section ?

**Comment by rithviknishad** [comment]
This issue is not present in the current deployment, right? Couldn't replicate it from my end. I believe this issue was caused by the code changes made to solve this issue.

Anyhow, you can fix it in the same PR.

**Comment by rudra321** [comment]
Hi, can you please review my PR?
