### ISSUE TITLE
Support for Loading Animation when filters are updated

### ISSUE THREAD

**Issue by rithviknishad** [ohcnetwork/leaderboard#438]
### Enter your suggestions in details:

Currently, when filters are applied (in the leaderboard and contributor activity timeline), it takes a while for results to be updated, there is no visual feedback indicating that the page is loading.

Add a loading animation when filters are applied.

Suggested package:
https://www.npmjs.com/package/next-nprogress-bar

**Comment by rudra321** [comment]
Hi @rithviknishad , I tried doing this but filters are being applied dynamically via routing. So I'm unable to get proper understanding as to at what point I need to apply this progress bar. Can you suggest please?

A video of what I've done in this, using next-nprogress-bar

https://github.com/coronasafe/leaderboard/assets/59362723/d95f9385-277d-48aa-a7f6-2858a0ab4908

**Comment by rithviknishad** [comment]
Closing as all pages are not static site generation
