### ISSUE TITLE
Twitter Icon Incorrect on Contributor Profile

### ISSUE THREAD

**Issue by its-harshitgoel** [ohcnetwork/leaderboard#484]
### Enter your suggestions in details:

Description:
The Twitter icon on the contributor profile page is outdated. This issue is present on the profiles of multiple contributors, as seen in the attached screenshot.

Steps to Reproduce:
Visit the (https://contributors.ohc.network/)
Observe the Twitter icon under the profiles of contributors.

Expected Behavior:
The Twitter icon should display the official and up-to-date logo of Twitter (X logo).

Actual Behavior:
The Twitter icon currently used does not match the official Twitter logo.

Screenshot:
![image](https://github.com/user-attachments/assets/69785fa4-c927-4ecf-9aa7-82920e4107bd)

Suggested Fix:
Replace the current Twitter icon with the official logo to ensure consistency.

**Comment by its-harshitgoel** [comment]
@dgparmar14 please assign this issue to me, i want to work on this.

**Comment by dgparmar14** [comment]
> @dgparmar14 please assign this issue to me, i want to work on this.

Hey, I'm not a maintainer. @rithviknishad is maintainer .

**Comment by its-harshitgoel** [comment]
@rithviknishad Please assign this to me!
