### ISSUE TITLE
Add Hover Effect on Google Summer Of  Code 

### ISSUE THREAD

**Issue by Indrajeety993648** [ohcnetwork/leaderboard#487]
### 1. What I expected to happen
When hovering over the "Google Summer of Code" section, I expected a visual hover effect to provide a better user experience by highlighting the section or providing additional visual feedback.

The hover effect is a common UI/UX feature that enhances the user's interaction with the site, making it more dynamic and engaging. Currently, there is no hover effect, which makes the site feel static and less interactive.

### 3. What I plan to do (Optional but better)
I plan to implement a simple CSS-based hover effect, such as changing the background color. This would improve the visual aesthetics and make the section more user-friendly.

## Screenshot 
![Screenshot from 2024-08-09 11-18-19](https://github.com/user-attachments/assets/67f9ed84-0d0c-4443-9714-2c043b359ba4)

### Additional Notes
Including hover effects on interactive elements like the "Google Summer of Code" section can significantly improve the user's experience by providing immediate visual feedback, making the website feel more responsive and polished.

**Comment by Indrajeety993648** [comment]
@rithviknishad  please assign this issue to me .

**Comment by rithviknishad** [comment]
@Indrajeety993648 feel free to take this issue up after following up on your stale PRs: https://github.com/coronasafe/leaderboard/pull/482, https://github.com/coronasafe/leaderboard/pull/481.

**Comment by Indrajeety993648** [comment]
@rithviknishad  please assign this issue to me .

**Comment by harshpanchal04** [comment]
Please assign this issue to me . I'd like to work upon this.

**Comment by harshpanchal04** [comment]
please assign this issue to me .

**Comment by abhinav26966** [comment]
Hey @rithviknishad, 
Is this issue still open? 
I would like to work on this issue, can you please assign this issue to me ?

**Comment by Indrajeety993648** [comment]
@rithviknishad   Sorry for the delay, I was a little busy for a few days. Now I can take this on and solve it as soon as possible.
