### ISSUE TITLE
While hovering over the badges of the contributors the UI is not theme aware.

### ISSUE THREAD

**Issue by aswinmurali-io** [ohcnetwork/leaderboard#516]
### Enter your suggestions in details:

Make the UI theme aware because I see this as a dark UI component in light theme and dark theme mode both.

### Light Theme
![image](https://github.com/user-attachments/assets/65f779c7-cb02-4d8e-b215-ff0399ad4e0b)

### Dark Theme
![image](https://github.com/user-attachments/assets/0e46f05e-6b28-413f-b774-9322c42464cd)

**Comment by Jash2606** [comment]
**Hey @rithviknishad** ,I'd like to contribute to this issue for Hacktoberfest . Could you please assign it to me?

**Comment by dharmik3504** [comment]
Hello @rithviknishad , ,I'd like to contribute to this issue for Hacktoberfest . Could you please assign it to me?

**Comment by Jash2606** [comment]
Hey @rithviknishad, 

While setting up a repo, I'm encountering an issue when I click on people in the Contributors page. It's showing an error. Could you guide me on how to
 resolve this?

![Screenshot 2024-10-01 113013](https://github.com/user-attachments/assets/806fcd38-280e-4508-a9c6-49bee1843a9f)

**Comment by rithviknishad** [comment]
Weird, we already have it exported.


<img width="942" alt="image" src="https://github.com/user-attachments/assets/85b3bce5-a7af-4a4d-b523-9405ae997bdb">

**Comment by Jash2606** [comment]
> Weird, we already have it exported.
> 
> <img alt="image" width="942" src="https://private-user-images.githubusercontent.com/25143503/372339252-85b3bce5-a7af-4a4d-b523-9405ae997bdb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3NjMzNDAsIm5iZiI6MTcyNzc2MzA0MCwicGF0aCI6Ii8yNTE0MzUwMy8zNzIzMzkyNTItODViM2JjZTUtYTdhZi00YTRkLWI1MjMtOTQwNWFlOTk3YmRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAxVDA2MTA0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4NTVhMTZhZjE3OTJmMjU3ZGQ3MjkzYjg3YzExODE5NjhmN2ZiN2I3MzJhYmM5OTQxNTQ5ODNhNzRjYWNmZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.90qC7Xlljjwt7z0T9yB5gWJ9TdFUHcytrWs0bVVRRF4">

Should I try by changing it to default export?

**Comment by rithviknishad** [comment]
Try pulling the latest main branch now; fixed in: https://github.com/ohcnetwork/leaderboard/commit/8c3cae9119227bf2c5c9c469d6648ee9067d1947

**Comment by dharmik3504** [comment]
Even i was facing same issue to resolve it i have just comment out the line no 56

Export const dynamicParams=false 

And than loaded the contributor page onces and then i was able to access /contributor/slug page

**Comment by rithviknishad** [comment]
Thanks @dharmik3504 ;

Updated in: https://github.com/ohcnetwork/leaderboard/commit/f5c735c37e767f2d4c7bf93ea0ff95bd988a11c8

**Comment by Jash2606** [comment]
Hey @rithviknishad , 
Can you review this preview for dark and light mode:
Dark:
![Screenshot 2024-10-01 121255](https://github.com/user-attachments/assets/8086fa87-dd2d-49fb-a12c-170244252e4f)
Light:
![Screenshot 2024-10-01 121241](https://github.com/user-attachments/assets/f492e8ff-5776-40e6-9c9a-230e2a863110)

**Comment by rithviknishad** [comment]
Try white for the creative thinking section to add more contrast with the green text.

Other than that LGTM

**Comment by Jash2606** [comment]
> Try white for the creative thinking section to add more contrast with the green and grey text.
> 
> Other than that LGTM

Hey @rithviknishad ,
Any other changes needed?
![image](https://github.com/user-attachments/assets/b510336e-62c3-436a-a75b-e3dd88920f17)

**Comment by rithviknishad** [comment]
loos good to me

**Comment by Jash2606** [comment]
Hey @rithviknishad ,
I had raised the PR #518 , Could you review it and Let me know if any changes required !
