### ISSUE TITLE
Responsiveness for Graduate Attributes in Contributor Page

### ISSUE THREAD

**Issue by gigincg** [ohcnetwork/leaderboard#523]
### URL:

https://contributors.ohc.network/contributors/gigincg

### Browser Name:

Arc

### Browser Version:

Version 1.63.1 (54714)

### Operating System:

Mac

### How to reproduce the issue:

Graduate Attributes are not responsive on Mobile Screens; Remove the Horizontal Scroll and wrap the Sections as different rows

![Image](https://github.com/user-attachments/assets/3fae1338-c78e-4816-9f78-8c29ea51cdfa)

**Comment by vinhyan** [comment]
Hi @gigincg! If nobody has been assigned, I'd like to give this a try please.

Thanks! :)
