### ISSUE TITLE
Support for filtering based leaderboard results based on URL params

### ISSUE THREAD

**Issue by rithviknishad** [ohcnetwork/leaderboard#526]
Currently the "search", "role" and "ordering" filters are applied based on a client side state. Update it such that instead of having a client side state, rely on the URL search params to maintain the state.

![Image](https://github.com/user-attachments/assets/6a136bcf-8e12-492c-b79d-ecdd488c0303)

**Comment by programmerraja** [comment]
can i work on this @rithviknishad ?

**Comment by programmerraja** [comment]
@rithviknishad can you check the PR #527
