### ISSUE TITLE
Leaderboard sort is not working

### ISSUE THREAD

**Issue by rithviknishad** [ohcnetwork/leaderboard#529]
Leaderboard sort is not working. It is being sorted by points, but changing it to any other value is not working.

### Steps to reproduce

1. Go to leaderboard page
2. Change from points to any other option
3. Observe the result set is not getting updated to the new sort.

![Image](https://github.com/user-attachments/assets/17c30ac1-cc9e-41c8-9eba-3050a6504208)

**Comment by programmerraja** [comment]
@rithviknishad can I work on this ?

**Comment by programmerraja** [comment]
@rithviknishad can you check #532
