### ISSUE TITLE
Duplicate PR collaboration activities

### ISSUE THREAD

**Issue by rithviknishad** [ohcnetwork/leaderboard#531]
Currently activities such as "PR collaboration" may get duplicated when the default branch gets merged to another branch such as `production`/`staging`. This misjudges collaboration activities.

### Proposed Solution

- Exclude PR activities where the base branch is the non-default branch of the repository.

![Image](https://github.com/user-attachments/assets/2f0c7334-7bd3-4208-a99c-76a9c85e5f48)

cc: @bodhish

**Comment by VAIBHAVSING** [comment]
@rithviknishad can you describe this issue in berif

**Comment by rithviknishad** [comment]
PR collaboration events should be tracked only for if the PR's base branch is the repository default branch

https://github.com/ohcnetwork/leaderboard/blob/6e38a436524cd71ca9a50cb51e84fe7a26564809/scraper/src/github-scraper/parseEvents.ts#L113-L120

**Comment by rithviknishad** [comment]
Are you facing any difficulties running the scraper?

**Comment by VAIBHAVSING** [comment]
@rithviknishad  i will not able run scrapper after pasting github token in that
![Image](https://github.com/user-attachments/assets/4fcc4d5c-c441-41b0-8760-0bc118d050b1)

**Comment by rithviknishad** [comment]
here's the command to run the scraper

```
GITHUB_TOKEN=$(gh auth token) pnpm dev ohcnetwork ../data-repo/data/github
```

**Comment by VAIBHAVSING** [comment]
@rithviknishad  can i completely ignore merge request from stagging or production branch or only ignore in above provided code at addcollaboration

**Comment by rithviknishad** [comment]
Didn't understand that, but whatever that was done in the PR is right.
