### ISSUE TITLE
Add EOD Report Count to Contributor Profiles on Leaderboard

### ISSUE THREAD

**Issue by aravindm4** [ohcnetwork/leaderboard#533]
### Enter your suggestions in details:

Enhance contributor profiles on the leaderboard by adding a count of EOD (End-of-Day) reports posted on the #care_eod Slack channel. 

This feature will improve tracking of contributor activity and engagement consistency.

**Comment by rithviknishad** [comment]
@aravindm4 we already have counts for each activity type for specified date range filter for contributor profile here. 

And the EOD scraper has just been enabled back, so it should start tracking from now on... https://github.com/ohcnetwork/leaderboard-data/commit/d3a618cce72137218e80280475e15ee0a2c1e534


![Image](https://github.com/user-attachments/assets/ce4b2b66-2168-4b80-ad10-caeaf82f84f1)

**Comment by rithviknishad** [comment]
Closing as completed by:

- https://github.com/ohcnetwork/leaderboard-data/commit/eb25b6cd83c9c87c8f89b0eb44069d291badd0a0
- https://github.com/ohcnetwork/leaderboard-data/commit/e6e634fe68af888cc0264d4eebf78f3decc87c32
