### ISSUE TITLE
GitHub Scraper: Skip review events for PR authors

### ISSUE THREAD

**Issue by rithviknishad** [ohcnetwork/leaderboard#536]
Currently, review events are captured from the events API, and even follow-up comments made by PR authors are treated as review events.

When appending events for "pr_reviewed"; skip appending for those who are the author of the PR.

https://github.com/ohcnetwork/leaderboard/blob/f0dcce4be322ddd00db3842e64eec47785cecea0/scraper/src/github-scraper/parseEvents.ts#L204-L211

**Comment by JavidSumra** [comment]
i would like to work on this issue

**Comment by AnveshNalimela** [comment]
@rithviknishad i would like on these issue But need some gudiance regarding the issue

**Comment by rithviknishad** [comment]
Sure, ask

**Comment by Srayash** [comment]
hey @rithviknishad, I've added a if statement which checks if the user and the PR author are same or not, and only appends `pr_reviewed` if they aren't same.
