### ISSUE TITLE
Ensure scraper does not fetch bot events

### ISSUE THREAD

**Issue by rithviknishad** [ohcnetwork/leaderboard#554]
https://github.com/ohcnetwork/leaderboard/blob/21a7beb26d93fd71f38d8ed7b78d86e5031d9296/scraper/src/github-scraper/fetchEvents.ts#L30-L32

![Image](https://github.com/user-attachments/assets/08891001-f058-43d9-bf7c-ab3f13cb1aa7)

**Comment by AdityaJ2305** [comment]
Hey @rithviknishad , I would like to work on this issue

**Comment by dharmik3504** [comment]
Hello @rithviknishad 
Can you review my PR please
