### ISSUE TITLE
Missing Hover Effect on Leaderboard Tab

### ISSUE THREAD

**Issue by AnveshNalimela** [ohcnetwork/leaderboard#565]
While navigating the website, I noticed that the hover effect is missing for the Leaderboard tab in the menu bar. On other pages, the hover effect works as expected and displays the activity status. However, this behavior is inconsistent when the user is on the Leaderboard page.

Steps to Reproduce
- Open the website.
- Navigate to the Leaderboard page.
- Hover over the Leaderboard tab in the menu bar.
-Observe the missing  activity status.

![Image](https://github.com/user-attachments/assets/dcd4574c-1536-4474-b50e-d3c23b5426db)

![Image](https://github.com/user-attachments/assets/124dc1c1-6a03-461f-8d1b-53f8989111bd)

**Comment by rithviknishad** [comment]
nice find!

**Comment by AnveshNalimela** [comment]
@rithviknishad  i would like to work on these issue
