### ISSUE TITLE
Optimize Search Field by Implementing Client-Side Filtering and Debouncing

### ISSUE THREAD

**Issue by i0am0arunava** [ohcnetwork/leaderboard#573]
### Enter your suggestions in details:

1. What I expected to happen:
I expected that network calls would be triggered only after the user finishes typing or after a brief delay, instead of on every keystroke. This would reduce unnecessary API requests and improve performance.

2. reason :
Currently, every keystroke triggers a network request, which can result in performance issues and an excessive number of calls to the server. This could cause slower response times, especially with large datasets or slower network connections.
(Optional: Attach a video or image of the current behavior if available)

3. What I plan to do (Optional but better):
I plan to implement debouncing using the use-bounce library or a client-side filtering solution rather than debouncing the network requests, . This will delay the network request until the user has stopped typing for a set duration, thus reducing the frequency of requests.

**Comment by i0am0arunava** [comment]
@rithviknishad can you assign this  to me

**Comment by rithviknishad** [comment]
we are already client side filtering btw.

we do not have cloudflare workers enabled.

just that it's simply dispatching requests to cloudflare pages and receiving same response regardless of the query params in the request.

**Comment by rithviknishad** [comment]
you could prevent fetching the same static content somehow

**Comment by rithviknishad** [comment]
content as in the response from cloudflare

**Comment by rithviknishad** [comment]
leaderboard is fully static site, it can't serve contents based on query params

**Comment by i0am0arunava** [comment]
> leaderboard is fully static site, it can't serve contents based on query params

You mentioned that static content is being served repeatedly, but the content is only loaded once when I first reload the page. I don't understand how it is being served again and again.

**Comment by rithviknishad** [comment]
<img width="858" alt="Image" src="https://github.com/user-attachments/assets/13cc7f1c-63bd-434e-8f88-0ca087d1d25e" />

**Comment by i0am0arunava** [comment]
> <img alt="Image" width="858" src="https://private-user-images.githubusercontent.com/25143503/398436423-13cc7f1c-63bd-434e-8f88-0ca087d1d25e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxMzAyNjQsIm5iZiI6MTczNTEyOTk2NCwicGF0aCI6Ii8yNTE0MzUwMy8zOTg0MzY0MjMtMTNjYzdmMWMtNjNiZC00MzRlLThmODgtMGNhMDg3ZDFkMjVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI1VDEyMzI0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3YzQ5YzllNzRmY2E3ODUyNGE2ZjMxY2IzNWE2YWY3MzA2NGJkNjFkODk3YzVlYTcwMGMyODIwYTA4NzZkNmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.AF6fgOeEiHGPbbnFppyjQ-4vyvRYr6-ZB53rQ76-EFA">

I menioned that every keystroke triggers a network request, but it is a static site and for serch operation no network calls are fired ,I understand this part .But your suggestion to prevent fetching the same static content during every keystroke for every key value—I cannot understand how different keystrokes would fetch the same content.

**Comment by rithviknishad** [comment]
so you are saying, right now different keystrokes are yielding different contents in each of the responses?

**Comment by i0am0arunava** [comment]
> so you are saying, right now different keystrokes are yielding different contents in each of the responses?

content are same but on each key stroke we are getting different number of contents

**Comment by rithviknishad** [comment]
are you sure?

<img width="1074" alt="Image" src="https://github.com/user-attachments/assets/0b1b8392-0724-4b2d-ad77-af33b91c1398" />

**Comment by i0am0arunava** [comment]
> are you sure?
> 
> <img alt="Image" width="1074" src="https://private-user-images.githubusercontent.com/25143503/398581423-0b1b8392-0724-4b2d-ad77-af33b91c1398.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxMzc2MjUsIm5iZiI6MTczNTEzNzMyNSwicGF0aCI6Ii8yNTE0MzUwMy8zOTg1ODE0MjMtMGIxYjgzOTItMDcyNC00YjJkLWFkNzctYWYzM2I5MWMxMzk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI1VDE0MzUyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiMGRkYzFiZmYzNDgwYWFhMjU1YzUzMzA1ZTlmYTgxMTI4YWQ3MTUyNjI3ODNlZWVjZGQ0ODNmNzc3NTE0YTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.o5XXZz33zLVj2G3xk_h6AE8IPGcy-Iw5VH4GOf8VhqM">

I think I had some misunderstanding regarding the word 'fetching.' Do you mean fetching from already available static content?

**Comment by i0am0arunava** [comment]
> are you sure?
> 
> <img alt="Image" width="1074" src="https://private-user-images.githubusercontent.com/25143503/398581423-0b1b8392-0724-4b2d-ad77-af33b91c1398.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxMzg0MjksIm5iZiI6MTczNTEzODEyOSwicGF0aCI6Ii8yNTE0MzUwMy8zOTg1ODE0MjMtMGIxYjgzOTItMDcyNC00YjJkLWFkNzctYWYzM2I5MWMxMzk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI1VDE0NDg0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5YTg0ZmEyY2YwYzkwNzAzMTI1ZjFjZTIxNzYxMWE3NzRkMmY2NDFlZGM2NTgwZTI4MmM2ZTZhOWVhOGU2N2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.WQY9AG1Unjf5tE39FTKqOuNaIKIxY8Ha4s0VwLr6kxI">

Now I understand the issue. In each search, the same size of data is being fetched, but I only need the data based on the search input, so that unnecessary data is not retrieved each time. I failed to understand it because in the UI it was showing different data.

**Comment by rithviknishad** [comment]
We don't even need to fetch on keystroke / filter change, since the static site generated already ships all the data for the specified date range, and it's client side filtered.

**Comment by i0am0arunava** [comment]
> We don't even need to fetch on keystroke / filter change in the first place, since the static site generated already ships all the data for the specified date range, and it's client side filtered.

one thing I could not understand 
As per your statement, there is no need to fetch data from the server every time a user types or changes a filter. Since the static site is pre-generated and includes all the necessary data for a specified date range, filtering can be done directly on the client side without making additional server requests. Why are these network requests being made during each keystroke? Are they unnecessary, and should I remove them?
![Image](https://github.com/user-attachments/assets/a5076afa-5849-4771-9734-cb96acac0683)

**Comment by rithviknishad** [comment]
like already said: https://github.com/ohcnetwork/leaderboard/issues/573#issuecomment-2559886933

**Comment by i0am0arunava** [comment]
> like already said: [#573 (comment)](https://github.com/ohcnetwork/leaderboard/issues/573#issuecomment-2559886933)

Finally, I understand this: we are performing client-side filtering during the search, but still fetching all the content from the server. What if I remove the logic that fetches data from the server during the search?
