### ISSUE TITLE
Search Bar Placeholder Hidden on Mobile

### ISSUE THREAD

**Issue by i0am0arunava** [ohcnetwork/leaderboard#577]
### Enter your suggestions in details:

The search bar should not hide the remaining part of the placeholder.
![Image](https://github.com/user-attachments/assets/57a3b89c-6439-4f86-9e97-49c7efb3216c)

**Comment by i0am0arunava** [comment]
@rithviknishad ,can I work on this?

**Comment by rithviknishad** [comment]
works fine for standard small devices

<img width="508" alt="Image" src="https://github.com/user-attachments/assets/cb06382b-05ed-4eb3-9c30-a9d25b9bf5e0" />
