### ISSUE TITLE
Care Icon in Footer not rendered properly

### ISSUE THREAD

**Issue by rajku-dev** [ohcnetwork/leaderboard#591]
### URL:

https://contributors.ohc.network/leaderboard/last-week

### Browser Name:

Chrome

### Browser Version:

131.0.6778.205

### Operating System:

Windows 11

### How to reproduce the issue:

Care icon in the footer is not being rendered properly.

**Comment by rajku-dev** [comment]
@rithviknishad I would like to fix this.

**Comment by DonXavierdev** [comment]
@rajku-dev i have already addressed this in #588
